apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zoer-plugin-runner-deny-network
spec:
  podSelector:
    matchLabels:
      zoer.plugin-runner: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
