apiVersion: v1
kind: ServiceAccount
metadata:
  name: zoer-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zoer-backend
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zoer-backend
subjects:
  - kind: ServiceAccount
    name: zoer-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zoer-backend
