apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eventscrape
resources:
  - namespace.yaml
  - convex.yaml
  - dashboard.yaml
  - admin.yaml
  - worker.yaml
  - certificate.yaml
  - ingress.yaml
